{{- range $ns := list .Values.modelRegistry.namespace "rhods-notebooks" "openshift-pipelines" "openshift-gitops-operator" "openshift-gitops" }}
{{- if eq (include "install-operators.shouldRenderNamespace" (dict "ns" $ns "root" $) | trim) "true" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns }}
  labels:
    {{- include "platform-addons.labels" $ | nindent 4 }}
{{- end }}
{{- end }}
