{{- if and .Values.maas.enabled (ne .Values.maas.createModelRef false) }}
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  name: {{ include "llminferenceservice.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    {{- include "llminferenceservice.labels" $ | nindent 4 }}
spec:
  modelRef:
    kind: LLMInferenceService
    name: {{ include "llminferenceservice.fullname" . }}
{{- end }}
