{{- $gc := .Values.disconnected.gatewayConfig | default dict }}
{{- $proxy := $gc.istioProxy | default dict }}
{{- $resources := $proxy.resources | default dict }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway-api.gatewayConfig.name" . }}
  namespace: {{ include "gateway-api.gatewayConfig.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  deployment: |
    spec:
      template:
        spec:
          containers:
          - name: istio-proxy
            resources:
{{- if $resources }}
{{- toYaml $resources | nindent 14 }}
{{- else }}
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: "2"
                memory: 2Gi
{{- end }}
            {{- if and $.Values.disconnected.enabled $gc.wasmInsecureRegistries }}
            env:
            - name: WASM_INSECURE_REGISTRIES
              value: {{ $gc.wasmInsecureRegistries | quote }}
            {{- end }}
  {{- if or $gc.serviceType $gc.servingCertSecretName }}
  service: |
    {{- if $gc.servingCertSecretName }}
    metadata:
      annotations:
        service.beta.openshift.io/serving-cert-secret-name: {{ $gc.servingCertSecretName | quote }}
    {{- end }}
    spec:
      type: {{ $gc.serviceType | default "ClusterIP" }}
  {{- end }}
