{{- range $name, $gw := .Values.gateways }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $name }}
  {{- with $gw.namespace }}
  namespace: {{ . }}
  {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  {{- with $gw.metadata }}
  {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  gatewayClassName: {{ $gw.gatewayClassName }}
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: {{ include "gateway-api.gatewayConfig.name" $ }}
  listeners:
    {{- range $lname, $listener := $gw.listeners }}
    {{- if $listener }}
    - name: {{ $lname }}
      hostname: {{ tpl $listener.hostname $ | quote }}
      port: {{ $listener.port }}
      protocol: {{ $listener.protocol }}
      {{- with $listener.tls }}
      tls:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      allowedRoutes:
      {{- if $listener.allowedRoutes }}
        {{- toYaml $listener.allowedRoutes | nindent 8 }}
      {{- else }}
        {{- include "gateway-api.defaultAllowedRoutes" $ | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
