{{- range $operator, $config := .Values.operators }}
{{- if and $config.namespace (eq (include "install-operators.shouldRenderNamespace" (dict "ns" $config.namespace "root" $) | trim) "true") }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $config.namespace }}
  labels:
    {{- include "install-operators.labels" $ | nindent 4 }}
  {{- with $config.namespaceLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $config.namespaceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
