#!/usr/bin/env bash
# Mint a MaaS API key with the current oc token and probe Granite over the gateway.
set -euo pipefail
# shellcheck source=common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

require_oc
warn_if_wrong_cluster
command -v python3 >/dev/null 2>&1 || { echo "python3 is required" >&2; exit 1; }
command -v curl >/dev/null 2>&1 || { echo "curl is required" >&2; exit 1; }

MODEL="${MODEL:-granite-3-1-2b-instruct}"
SUBSCRIPTION="${SUBSCRIPTION:-free-models-subscription}"
PROMPT="${PROMPT:-Reply with a single word: pong}"
MAX_TOKENS="${MAX_TOKENS:-16}"
KEY_NAME="${KEY_NAME:-opentlc-lab-probe}"

maas_host() {
  local domain
  domain="$(oc get ingresses.config.openshift.io cluster -o jsonpath='{.spec.domain}' 2>/dev/null || true)"
  if [[ -n "${domain}" ]]; then
    echo "maas.${domain}"
    return
  fi
  python3 -c 'import yaml,sys
c=yaml.safe_load(open(sys.argv[1]))["global"]["cluster"]
print("maas.apps.{}.{}".format(c["name"], c["baseDomain"]))' "${CLUSTER}/cluster.yaml"
}

json_field() {
  python3 -c 'import json,sys
obj=json.load(sys.stdin)
for key in sys.argv[1:]:
    if not isinstance(obj, dict):
        obj=""
        break
    obj=obj.get(key, "")
if obj is None:
    obj=""
print(obj if not isinstance(obj, (dict, list)) else json.dumps(obj))' "$@"
}

CURL_OPTS=(-skS --http1.1 --connect-timeout 20 --max-time 120)

http_code() {
  local url="$1"
  shift
  curl -skS --http1.1 --connect-timeout 8 --max-time 15 -o /dev/null -w "%{http_code}" "$@" "${url}" 2>/dev/null || echo "000"
}

# Gateway Service is LoadBalancer:80 only. https://maas.apps.*:443 times out when
# traffic never reaches the OpenShift router. Fall back to the Gateway ELB on
# HTTP/80 with the public Host header so Envoy matches the listener hostname.
select_base_url() {
  local code addr
  echo "  probing https://${HOST}/" >&2
  code="$(http_code "https://${HOST}/")"
  if [[ "${code}" != "000" ]]; then
    echo "  using https://${HOST} (HTTP ${code})" >&2
    echo "https://${HOST}"
    return
  fi
  echo "  https://${HOST} timed out" >&2

  echo "  probing http://${HOST}/ (no redirect follow)" >&2
  code="$(http_code "http://${HOST}/")"
  if [[ "${code}" != "000" && "${code}" != "301" && "${code}" != "302" && "${code}" != "307" && "${code}" != "308" ]]; then
    echo "  using http://${HOST} (HTTP ${code})" >&2
    echo "http://${HOST}"
    return
  fi

  addr="$(oc get gateway maas-default-gateway -n openshift-ingress -o jsonpath='{.status.addresses[0].value}' 2>/dev/null || true)"
  if [[ -n "${addr}" ]]; then
    echo "  probing http://${addr}/ Host=${HOST}" >&2
    code="$(http_code "http://${addr}/" -H "Host: ${HOST}")"
    if [[ "${code}" != "000" ]]; then
      echo "  using http://${addr} (HTTP ${code})" >&2
      echo "http://${addr}"
      return
    fi
    echo "  Gateway ELB http://${addr} also failed (HTTP ${code})" >&2
  fi
  echo "https://${HOST}"
}

curl_json() {
  local method="$1" url="$2" body="${3:-}" token="$4"
  local tmp err code
  tmp="$(mktemp)"
  err="$(mktemp)"
  if [[ -n "${body}" ]]; then
    code="$(curl "${CURL_OPTS[@]}" -o "${tmp}" -w "%{http_code}" -X "${method}" "${url}" \
      -H "Host: ${HOST}" \
      -H "Authorization: Bearer ${token}" \
      -H "Content-Type: application/json" \
      -d "${body}" 2>"${err}")" || true
  else
    code="$(curl "${CURL_OPTS[@]}" -o "${tmp}" -w "%{http_code}" -X "${method}" "${url}" \
      -H "Host: ${HOST}" \
      -H "Authorization: Bearer ${token}" \
      -H "Content-Type: application/json" 2>"${err}")" || true
  fi
  if [[ -s "${err}" ]]; then
    echo "  curl: $(tr '\n' ' ' < "${err}")" >&2
  fi
  rm -f "${err}"
  echo "${code}" "${tmp}"
}

dump_gateway() {
  echo "== Gateway / Route diagnostics ==" >&2
  oc get gateway maas-default-gateway -n openshift-ingress -o wide 2>&1 >&2 || true
  oc get gateway maas-default-gateway -n openshift-ingress \
    -o jsonpath='{range .status.listeners[*]}{.name}{" protocol="}{.supportedKinds}{" attached="}{.attachedRoutes}{"\n"}{end}' 2>/dev/null >&2 || true
  oc describe gateway maas-default-gateway -n openshift-ingress 2>&1 | grep -A2 -E 'Listeners|Hostname|Programmed|ResolvedRefs|NoCertificate|secret' >&2 || true
  oc get route -n openshift-ingress 2>&1 >&2 || true
  oc get secret maas-default-gateway-tls -n openshift-ingress 2>&1 >&2 || true
  oc get svc -n openshift-ingress -l gateway.networking.k8s.io/gateway-name=maas-default-gateway 2>&1 >&2 || true
}

fail=0
HOST="$(maas_host)"
OC_TOKEN="$(oc whoami -t)"

echo "== MaaS host =="
echo "  ${HOST}"
echo "  user: $(oc whoami)"
BASE_URL="$(select_base_url)"
MAAS_API="${BASE_URL}/maas-api"
echo "  base: ${BASE_URL}"

if [[ -z "${MAAS_API_KEY:-}" ]]; then
  echo "== Mint API key =="
  echo "  POST ${MAAS_API}/v1/api-keys  (subscription=${SUBSCRIPTION})"
  mint_body="$(python3 -c 'import json,sys; print(json.dumps({
    "name": sys.argv[1],
    "description": "Generated by probe-maas.sh",
    "subscription": sys.argv[2],
    "ephemeral": True,
    "expiresIn": "1h",
  }))' "${KEY_NAME}" "${SUBSCRIPTION}")"
  read -r mint_code mint_file < <(curl_json POST "${MAAS_API}/v1/api-keys" "${mint_body}" "${OC_TOKEN}")
  mint_body_out="$(cat "${mint_file}")"
  rm -f "${mint_file}"
  echo "  HTTP ${mint_code}"
  echo "${mint_body_out}" | python3 -m json.tool 2>/dev/null || echo "${mint_body_out}"
  if [[ "${mint_code}" != "200" && "${mint_code}" != "201" ]]; then
    echo "FAIL minting API key (HTTP ${mint_code})" >&2
    dump_gateway
    echo >&2
    echo "The Gateway Service only listens on :80. If https://${HOST}:443 times out," >&2
    echo "the probe should fall back to the Gateway LoadBalancer HTTP address." >&2
    echo "Check: oc get gateway,route,svc -n openshift-ingress" >&2
    exit 1
  fi
  MAAS_API_KEY="$(echo "${mint_body_out}" | json_field key)"
  if [[ -z "${MAAS_API_KEY}" || "${MAAS_API_KEY}" == "null" ]]; then
    echo "FAIL response had no .key" >&2
    exit 1
  fi
  echo
  echo "  export MAAS_API_KEY='${MAAS_API_KEY}'"
else
  echo "== Using existing MAAS_API_KEY =="
fi

echo
echo "== GET /v1/models =="
read -r models_code models_file < <(curl_json GET "${BASE_URL}/v1/models" "" "${MAAS_API_KEY}")
models_out="$(cat "${models_file}")"
rm -f "${models_file}"
echo "  HTTP ${models_code}"
echo "${models_out}" | python3 -m json.tool 2>/dev/null || echo "${models_out}"
if [[ "${models_code}" != "200" ]]; then
  echo "FAIL listing models (HTTP ${models_code})" >&2
  fail=1
fi

echo
echo "== POST /v1/chat/completions  (model=${MODEL}) =="
chat_body="$(python3 -c 'import json,sys; print(json.dumps({
    "model": sys.argv[1],
    "messages": [{"role": "user", "content": sys.argv[2]}],
    "max_tokens": int(sys.argv[3]),
}))' "${MODEL}" "${PROMPT}" "${MAX_TOKENS}")"
read -r chat_code chat_file < <(curl_json POST "${BASE_URL}/v1/chat/completions" "${chat_body}" "${MAAS_API_KEY}")
chat_out="$(cat "${chat_file}")"
rm -f "${chat_file}"
echo "  HTTP ${chat_code}"
echo "${chat_out}" | python3 -m json.tool 2>/dev/null || echo "${chat_out}"
if [[ "${chat_code}" != "200" ]]; then
  echo "FAIL chat completions (HTTP ${chat_code})" >&2
  fail=1
fi

exit "${fail}"
