{{- if not (lookup "operators.coreos.com/v1" "OperatorGroup" .Values.operatorNamespace "cert-manager-operator") }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cert-manager-operator
  namespace: {{ .Values.operatorNamespace }}
spec:
  upgradeStrategy: Default
  targetNamespaces:
    - {{ .Values.operatorNamespace | quote }}
{{- end }}
